### ISSUE TITLE
Change the Interface for Credentials

### ISSUE THREAD

**Issue by mfrost503** [mfrost503/Snaggle#14]
I'd like to move away from the accessor methods for the Credentials...which would probably eliminate that interface as well. They are essentially Value Objects - so I'll like to move to:
```
$consumer = new ConsumerCredentials('KEY', 'SECRET');
```
This could be introduced with the current interface by defaulting the values to an empty string...if the setters come out, this change would be breaking and be required to jump a major version - to 1.0.0

**Comment by localheinz** [comment]
@mfrost503 

When referring to *accessors* - do you mean *mutators*? Because you'd still need to access the values of the value object. Asking for a friend!!!11

**Comment by mfrost503** [comment]
@localheinz - yeah the mutators would need to go the accessors would definitely have to stay. My only concern would be taking the mutators out, in the event that someone is already using that interface. Ideally, I'd like to add it to the constructors...but I think that'd be sloppy to do that and keep the mutators...

I think it's an easy enough fix from an implementation standpoint, I'm thinking taking the mutators out and bumping to major version 1.0.0 (there's something with the post fields I think I'm gonna have to roll in too) - that seems like the best way to go, what do you think?

**Comment by mfrost503** [comment]
@localheinz It seems like 109 installs (via packagist) is considerable to enough to not just go breaking stuff :P

**Comment by localheinz** [comment]
@mfrost503 

Good job!

Here's how I think it would be appropriate to do it (note however, that I personally haven't done it before as I've never published something publicly on GitHub really that broke an API, but I've seen a bit of it here and there):

* [ ] make sure all of the implementations of `CredentialInterface` are covered by a test like [this one here for `RequestCredentials`](https://github.com/mfrost503/Snaggle/blob/master/tests/Client/Credentials/RequestCredentialsTest.php#L30-L34) in order to avoid regressions
* [ ] add a constructor to these implementations that accepts `$identifier` and `$secret` with `''` as default value (with that, also make sure you add tests that ensure that they can be set by constructor injection)
* [ ] mark the corresponding mutators `setIdentifier()` and `setCredentials()` as `@deprecated`

### Bonus points

* [ ] with marking `@deprecated`, add a note why that's happening and when (tag?) they will be removed and that instead, constructor injection should be used
* [ ] maybe even derive an `AbstractCredentials` to avoid to repeat yourself (constructor, mutator, accessor), although this should probably be a separate PR
* [ ] maybe even derive an `AbstractCredentialsTestCase` to avoid to repeat yourself

What do you think? I have confidence!

**Comment by mfrost503** [comment]
@localheinz: so I'm reading through this, as I get prepared for a 1.0.0 release - I  see the deprecation notices, does it make sense to do a pre 1.0.0 tag with the constructor changes? I mean it shouldn't matter unless users aren't specifying a specific version in composer.json - I like all these changes. I'm thinking I could tag 1.0.0 - with the mutators in there and remove the mutators in a future release. Curious for your thoughts.

**Comment by localheinz** [comment]
@mfrost503 

To be honest, I have never before worked on something that was OSS **and** deprecated a feature, so I'm actually quite unsure how to proceed with the tagging. On the other hand, maybe it's ok to just go ahead with `0.4.0` for now, what do you think?

According to http://semver.org, what has happened in the last days calls for a *MINOR* update, I think.

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by mfrost503** [comment]
@localheinz So what I'm thinking makes sense is to tag it 0.3.0 and leave the mutators in place. Leave the deprecation notices in place. Once I get a chance to take a bit more inventory and perhaps some other things...I'll remove the mutators, remove the default param values and type hint them to CredentialInterface - I think I'd like to take this work that's been done and release it. Even if I don't have many other changes to make, that seems like a pretty good point to go to 1.0.0

**Comment by localheinz** [comment]
@mfrost503 

Sorry, my bad - of course I mean `0.3.0`! :+1:

**Comment by mfrost503** [comment]
@localheinz - Just tagged 0.3.0 - feel like a lot of things got cleaned up and some duplication went away - all the tests were looking good! Many thanks for your help, 0.3.0 is a definite improvement - pretty clear path to 1.0.0. Pretty awesome!

**Comment by localheinz** [comment]
@mfrost503 

You're much welcome! Let me know if I can be of more help, ok?
